---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      Web:
        patterns:
          - "Microsoft.AspNetCore.Components.WebAssembly"
          - "Microsoft.AspNetCore.Components.WebAssembly.Authentication"
          - "Microsoft.FluentUI.AspNetCore.Components"
          - "Microsoft.FluentUI.AspNetCore.Components.Icons"
      AppHost:
        patterns:
          - "Aspire.Hosting.AppHost"
          - "Microsoft.AspNetCore.Components.WebAssembly.DevServer"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      Actions:
        patterns:
          - "*"
