name: Build Client Artifact

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: |
          cd BlazorWasmOsmOauth
          dotnet publish BlazorWasmOsmOauth.csproj --configuration Release --property PublishDir=../publish/
          cd ..

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v5
        with:
          name: wasm-client
          path: ./publish